# Generated by Django 5.2.5 on 2025-09-03 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_item', models.CharField(max_length=100)),
                ('barcode', models.IntegerField(unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('number_of_units', models.IntegerField()),
                ('vat_status', models.CharField(choices=[('VAT INCLUSIVE', 'VAT'), ('VAT EXCLUSIVE', 'NO VAT')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyDet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('company_tin', models.CharField(max_length=12, unique=True)),
                ('company_username', models.CharField(max_length=50)),
                ('company_email', models.EmailField(max_length=100)),
                ('company_phoneNo', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Receiptentry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_inquired', models.IntegerField()),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_tax', models.DecimalField(decimal_places=2, max_digits=12)),
                ('customer_name', models.CharField(max_length=100)),
                ('phone_number', models.IntegerField()),
                ('receipt_no', models.CharField(max_length=20)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='myapp.items')),
            ],
        ),
    ]
